url: ""
baseurl: ""
title: "The Red Monkey"
description: "Your local pub"

collections:
  events:
    output: true
    permalink: /events/:slug/
  beers:
    output: true
    permalink: /beers/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "beers"
    values:
      layout: "beer"
